const demoUser={username:"agent0247",password:"secret123",name:"Alex Morgan",matricule:"SS-0247",grade:"Agent Spécial",unit:"Protection rapprochée",status:"EN SERVICE"};
let state={page:"dashboard",logged:false,user:demoUser};
const pages={dashboard:"Tableau de bord",profile:"Mon profil",missions:"Missions",reports:"Rapports",documents:"Documentation",vehicles:"Véhicules",announcements:"Communications",employees:"Employés",admin:"Administration"};

document.addEventListener("DOMContentLoaded",()=>{
 document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>{state.page=b.dataset.page;render()}));
 document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();const u=document.getElementById("username").value,p=document.getElementById("password").value;if(u===demoUser.username&&p===demoUser.password){state.logged=true;sessionStorage.setItem("ssLogged","1");render()}else alert("Identifiants incorrects. Utilisez la démo affichée.")});
 if(sessionStorage.getItem("ssLogged"))state.logged=true; render();
});
function render(){document.getElementById("login").style.display=state.logged?"none":"grid";document.getElementById("app").style.display=state.logged?"block":"none";if(!state.logged)return;document.getElementById("pageTitle").textContent=pages[state.page]||"Portail";document.getElementById("userMini").textContent=state.user.name;document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===state.page));document.querySelectorAll(".admin-only").forEach(b=>b.style.display=state.user.grade.includes("Directeur")?"block":"none");document.getElementById("content").innerHTML=views[state.page]?views[state.page]():views.dashboard();}
function logout(){sessionStorage.removeItem("ssLogged");state.logged=false;render()}function toggleSidebar(){document.querySelector(".sidebar").classList.toggle("open")}
const views={
dashboard:()=>`<div class="page-head"><div><h1>Bonjour, ${state.user.name.split(" ")[0]}.</h1><p>Bienvenue sur le portail interne du Secret Service.</p></div><span class="badge green">● SYSTÈME OPÉRATIONNEL</span></div>
<div class="grid stats"><div class="card stat"><div class="label">MISSIONS ACTIVES</div><div class="value">04</div><div class="sub">2 vous sont affectées</div></div><div class="card stat"><div class="label">RAPPORTS À TRAITER</div><div class="value">02</div><div class="sub">Dernière mise à jour : aujourd'hui</div></div><div class="card stat"><div class="label">AGENTS EN SERVICE</div><div class="value">18</div><div class="sub">Sur 27 agents enregistrés</div></div><div class="card stat"><div class="label">ALERTES</div><div class="value">01</div><div class="sub">Priorité normale</div></div></div>
<div class="grid two" style="margin-top:18px"><div class="card"><h3 class="section-title">Missions récentes</h3><div class="list"><div class="item"><div><b>Protection — Convoi VIP</b><small>Aéroport → Downtown • 22:00</small></div><span class="badge gold">EN COURS</span></div><div class="item"><div><b>Sécurisation événement</b><small>Palais des congrès • 20:30</small></div><span class="badge green">PLANIFIÉE</span></div><div class="item"><div><b>Surveillance site</b><small>Site fédéral • 18:00</small></div><span class="badge">TERMINÉE</span></div></div></div><div class="card"><h3 class="section-title">Note de service</h3><div class="notice"><b>Rappel opérationnel</b><p class="muted">Tous les agents doivent vérifier leur équipement avant prise de service.</p><small>Direction • Aujourd'hui 16:40</small></div></div></div>`,
profile:()=>`<div class="page-head"><div><h1>Mon profil</h1><p>Dossier administratif et informations de service.</p></div></div><div class="profile"><div class="card profile-card"><div class="big-avatar">AM</div><h2>${state.user.name}</h2><span class="badge green">${state.user.status}</span><p class="muted">${state.user.grade}</p><button class="btn">Modifier le profil</button></div><div class="card"><h3 class="section-title">Informations agent</h3><div class="kv"><div><small>Matricule</small><b>${state.user.matricule}</b></div><div><small>Grade</small><b>${state.user.grade}</b></div><div><small>Unité</small><b>${state.user.unit}</b></div><div><small>Date d'entrée</small><b>14/06/2026</b></div><div><small>Statut</small><b>Actif</b></div><div><small>Habilitation</small><b>Niveau 3</b></div></div></div></div>`,
missions:()=>`<div class="page-head"><div><h1>Missions</h1><p>Suivi des opérations et affectations.</p></div><button class="primary" onclick="alert('Création de mission : fonction à connecter à la base de données.')">+ Nouvelle mission</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Mission</th><th>Zone</th><th>Horaire</th><th>Statut</th><th>Responsable</th></tr></thead><tbody><tr><td><b>Protection Convoi VIP</b></td><td>Aéroport / Downtown</td><td>22:00</td><td><span class="badge gold">En cours</span></td><td>SS-0191</td></tr><tr><td><b>Sécurisation événement</b></td><td>Palais des congrès</td><td>20:30</td><td><span class="badge green">Planifiée</span></td><td>SS-0124</td></tr><tr><td><b>Surveillance site</b></td><td>Site fédéral</td><td>18:00</td><td><span class="badge">Terminée</span></td><td>SS-0247</td></tr></tbody></table></div>`,
reports:()=>`<div class="page-head"><div><h1>Rapports</h1><p>Rapports d'intervention et comptes rendus.</p></div><button class="primary" onclick="alert('Formulaire de rapport : à connecter à la base de données.')">+ Nouveau rapport</button></div><div class="grid two"><div class="card"><h3 class="section-title">Mes rapports</h3><div class="list"><div class="item"><div><b>Rapport #RP-1042</b><small>Protection convoi • 25/09/2026</small></div><span class="badge green">VALIDÉ</span></div><div class="item"><div><b>Rapport #RP-1038</b><small>Surveillance site • 24/09/2026</small></div><span class="badge gold">À VALIDER</span></div></div></div><div class="card"><h3 class="section-title">Rappel</h3><div class="notice danger"><b>Rapport obligatoire</b><p class="muted">Tout incident ou intervention doit faire l'objet d'un rapport avant la fin du service.</p></div></div></div>`,
documents:()=>`<div class="page-head"><div><h1>Documentation</h1><p>Procédures, règlements et ressources internes.</p></div></div><div class="grid three">${["Règlement interne","Code de conduite","Procédure d'intervention","Protocole protection VIP","Procédure radio","Manuel de formation"].map((x,i)=>`<div class="card"><div style="font-size:24px;color:var(--gold)">▤</div><h3>${x}</h3><p class="muted">Document interne • Version ${i+1}.0</p><button class="btn">Consulter</button></div>`).join("")}</div>`,
vehicles:()=>`<div class="page-head"><div><h1>Véhicules</h1><p>Parc automobile et affectations.</p></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>Véhicule</th><th>Immatriculation</th><th>État</th><th>Affectation</th></tr></thead><tbody><tr><td>Bravado Buffalo STX</td><td>SS-042</td><td><span class="badge green">Disponible</span></td><td>—</td></tr><tr><td>Granger 3600LX</td><td>SS-017</td><td><span class="badge gold">En mission</span></td><td>SS-0191</td></tr><tr><td>Schafter V12</td><td>SS-031</td><td><span class="badge green">Disponible</span></td><td>—</td></tr></tbody></table></div>`,
announcements:()=>`<div class="page-head"><div><h1>Communications</h1><p>Notes de service et annonces de la direction.</p></div></div><div class="list"><div class="card"><span class="badge gold">DIRECTION</span><h3>Briefing général — 27/09</h3><p class="muted">Tous les agents affectés aux opérations de protection sont convoqués à 20:00 en salle de briefing.</p><small class="muted">Publié aujourd'hui à 15:20</small></div><div class="card"><span class="badge">INFORMATION</span><h3>Mise à jour des procédures radio</h3><p class="muted">La nouvelle procédure radio est disponible dans la documentation.</p><small class="muted">Publié hier à 18:05</small></div></div>`,
employees:()=>`<div class="page-head"><div><h1>Employés</h1><p>Gestion du personnel du Secret Service.</p></div><button class="primary">+ Ajouter un agent</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Agent</th><th>Matricule</th><th>Grade</th><th>Unité</th><th>Statut</th></tr></thead><tbody>${[["Alex Morgan","SS-0247","Agent Spécial","Protection","En service"],["Jordan Reed","SS-0191","Officier","Protection","En service"],["Taylor Brooks","SS-0124","Agent Senior","Renseignement","Hors service"],["Morgan Lee","SS-0302","Recrue","Support","Formation"]].map(a=>`<tr><td><div class="person"><div class="avatar">${a[0].split(" ").map(x=>x[0]).join("")}</div><b>${a[0]}</b></div></td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td><td><span class="badge ${a[4]=="En service"?"green":""}">${a[4]}</span></td></tr>`).join("")}</tbody></table></div>`,
admin:()=>`<div class="page-head"><div><h1>Administration</h1><p>Centre de contrôle de l'agence.</p></div></div><div class="grid stats"><div class="card stat"><div class="label">AGENTS</div><div class="value">27</div></div><div class="card stat"><div class="label">MISSIONS</div><div class="value">142</div></div><div class="card stat"><div class="label">RAPPORTS</div><div class="value">389</div></div><div class="card stat"><div class="label">VÉHICULES</div><div class="value">18</div></div></div><div class="grid three" style="margin-top:18px"><div class="card"><h3>Gestion du personnel</h3><p class="muted">Grades, unités, statuts et habilitations.</p><button class="btn gold" onclick="state.page='employees';render()">Ouvrir</button></div><div class="card"><h3>Gestion des missions</h3><p class="muted">Créer, modifier et affecter les opérations.</p><button class="btn gold">Ouvrir</button></div><div class="card"><h3>Paramètres</h3><p class="muted">Configuration du portail et permissions.</p><button class="btn gold">Ouvrir</button></div></div>`
};
