const URL="https://awdrxzsilfdnvqyclkgr.supabase.co";
const KEY="sb_publishable_t6igA1TjhwPcaLADblP9OQ_V_ptyi-t";
const sb=supabase.createClient(URL,KEY);let me=null,profiles=[],page="dashboard";
const labels={dashboard:"Tableau de bord",profile:"Mon profil",missions:"Missions",reports:"Rapports",documents:"Documentation",vehicles:"Véhicules",communications:"Communications",employees:"Employés",accounts:"Comptes & permissions",admin:"Administration"};
loginForm.onsubmit=async e=>{e.preventDefault();err.textContent="";const r=await sb.auth.signInWithPassword({email:email.value.trim(),password:password.value});if(r.error){err.textContent="Connexion impossible : "+r.error.message;return}start()};
async function start(){const u=(await sb.auth.getUser()).data.user;if(!u)return;const r=await sb.from("profiles").select("*").eq("id",u.id).single();if(r.error){err.textContent="Profil introuvable : "+r.error.message;await sb.auth.signOut();return}me=r.data;if(!me.actif){err.textContent="Compte désactivé.";await sb.auth.signOut();return}login.hidden=true;app.hidden=false;await load();buildNav();render()}
async function load(){if(me.role==="Direction"||me.role==="Administration"){const r=await sb.from("profiles").select("*").order("created_at");profiles=r.data||[]}else profiles=[me]}
function can(x){return me.role==="Direction"||!!me[x]}function boss(){return me.role==="Direction"||me.role==="Administration"}
function buildNav(){let a=[["dashboard","⌂ Tableau de bord"],["profile","♙ Mon profil"],["missions","▣ Missions"],["reports","▤ Rapports"],["documents","▥ Documentation"],["vehicles","▰ Véhicules"],["communications","◈ Communications"]];if(can("permission_employes"))a.push(["employees","♙ Employés"]);if(can("permission_comptes"))a.push(["accounts","⚿ Comptes & permissions"]);if(boss())a.push(["admin","⚙ Administration"]);nav.innerHTML=a.map(x=>`<button data-p="${x[0]}" onclick="go('${x[0]}')">${x[1]}</button>`).join("")}
function go(p){page=p;render()}function toggleMenu(){document.querySelector("aside").classList.toggle("open")}async function logout(){await sb.auth.signOut();location.reload()}
function head(a,b,c=""){return `<div class="head"><div><h1>${a}</h1><p>${b}</p></div>${c}</div>`}
function render(){title.textContent=labels[page];who.textContent=`${me.nom_rp} • ${me.role}`;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.p===page));view.innerHTML=views[page]()}
const views={
dashboard:()=>head("Tableau de bord",`Bienvenue, ${me.nom_rp}.`)+`<div class="grid stats"><div class="card stat"><small>MISSIONS ACTIVES</small><strong>04</strong></div><div class="card stat"><small>RAPPORTS</small><strong>12</strong></div><div class="card stat"><small>COMPTES</small><strong>${profiles.length}</strong></div><div class="card stat"><small>ACCÈS</small><strong style="font-size:18px">${me.role}</strong></div></div><div class="grid two" style="margin-top:16px"><div class="card"><h3>Opérations</h3><p class="notice">Protection — Convoi VIP</p><p class="notice">Sécurisation événement</p></div><div class="card"><h3>Direction</h3><p class="muted">Portail connecté à Supabase.</p></div></div>`,
profile:()=>head("Mon profil","Informations du compte.")+`<div class="card"><h2>${me.nom_rp}</h2><p><b>Matricule :</b> ${me.matricule||"—"}</p><p><b>Rôle :</b> ${me.role}</p><span class="badge green">ACTIF</span></div>`,
missions:()=>head("Missions","Gestion des opérations.")+`<div class="card"><p class="notice">Protection Convoi VIP <span class="badge gold">EN COURS</span></p></div>`,
reports:()=>head("Rapports","Comptes rendus.")+`<div class="card"><p>RP-1042 — Protection convoi <span class="badge green">VALIDÉ</span></p></div>`,
documents:()=>head("Documentation","Règlements et procédures.")+`<div class="card"><h3>Règlement interne</h3></div>`,
vehicles:()=>head("Véhicules","Parc automobile.")+`<div class="card"><p>Buffalo STX — SS-042 <span class="badge green">DISPONIBLE</span></p></div>`,
communications:()=>head("Communications","Annonces de la Direction.")+`<div class="card"><h3>Briefing général</h3></div>`,
employees:()=>head("Employés","Personnel enregistré.")+table(false),
accounts:()=>head("Comptes & permissions","Modification des rôles et permissions.")+table(true),
admin:()=>head("Administration","Centre de contrôle Direction.")+`<div class="grid stats"><div class="card stat"><small>COMPTES</small><strong>${profiles.length}</strong></div><div class="card stat"><small>ACTIFS</small><strong>${profiles.filter(x=>x.actif).length}</strong></div><div class="card stat"><small>DIRECTION</small><strong>${profiles.filter(x=>x.role==="Direction").length}</strong></div><div class="card stat"><small>AGENTS</small><strong>${profiles.filter(x=>x.role==="Agent").length}</strong></div></div>`
};
function table(actions){return `<div class="card tablewrap"><table class="table"><thead><tr><th>Nom RP</th><th>Matricule</th><th>Rôle</th><th>Statut</th>${actions?"<th>Action</th>":""}</tr></thead><tbody>${profiles.map(p=>`<tr><td>${p.nom_rp}</td><td>${p.matricule||"—"}</td><td>${p.role}</td><td><span class="badge ${p.actif?"green":"red"}">${p.actif?"ACTIF":"DÉSACTIVÉ"}</span></td>${actions?`<td><button class="btn" onclick="edit('${p.id}')">Modifier</button></td>`:""}</tr>`).join("")}</tbody></table></div>`}
function edit(id){const p=profiles.find(x=>x.id===id);editId.value=id;eName.value=p.nom_rp;eBadge.value=p.matricule||"";eRole.value=p.role;eActive.checked=p.actif;pm.checked=p.permission_missions;pr.checked=p.permission_rapports;pe.checked=p.permission_employes;pc.checked=p.permission_comptes;modal.hidden=false}
function closeModal(){modal.hidden=true}
editForm.onsubmit=async e=>{e.preventDefault();formErr.textContent="";const data={nom_rp:eName.value.trim(),matricule:eBadge.value.trim(),role:eRole.value,actif:eActive.checked,permission_missions:pm.checked,permission_rapports:pr.checked,permission_employes:pe.checked,permission_comptes:pc.checked};const r=await sb.from("profiles").update(data).eq("id",editId.value);if(r.error){formErr.textContent=r.error.message;return}closeModal();await load();me=profiles.find(x=>x.id===me.id)||me;buildNav();render()}
sb.auth.getSession().then(x=>{if(x.data.session)start()});